### PR TITLE
[webgpu] Update shader to support non module-level scoping function

### LINKED ISSUE #6842: LayersModel#predict() results in all zeros when using WebGPU backend in Deno
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): https://cdn.skypack.dev/@tensorflow/tfjs
- TensorFlow.js version (use command below): 3.20.0
- Browser version: Deno (built from source at commit 2929ec9f)
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**

I came from https://github.com/tensorflow/tfjs/issues/6746 and made https://github.com/denoland/deno/pull/15853 to have deno compatible with the WebGPU backend. Model predictions sometimes resulting in an all-zeros tensor, the problem does not exist with a CPU backend.

**Describe the expected behavior**

Output tensors should contain non-zero numbers.

**Standalone code to reproduce the issue**

```ts
import * as tf from "https://cdn.skypack.dev/@tensorflow/tfjs?dts";
import "https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu";

await tf.ready();
const model = tf.sequential();
model.add(tf.layers.dense({ units: 1, inputShape: [1] });
const output = await model.predict(tf.tensor([1])).array();

console.log(output); // prints [[0]]
```

**Other info / logs**
I am on an Apple M1 laptop.

Backstory and tracking issues:
1. Deno uses [`deno_webgpu`](https://github.com/gfx-rs/wgpu/tree/master/deno_webgpu) from [`gfx-rs/wgpu`](https://github.com/gfx-rs/wgpu), which in turn uses [`gfx-rs/naga`](https://github.com/gfx-rs/naga) for all [*shader related things*](https://github.com/gfx-rs/wgpu/issues/2994#issuecomment-1229594822).
2. gfx-rs/wgpu#2994
3. gfx-rs/naga#2072
4. gfx-rs/naga#2071
5. gfx-rs/naga#1829
6. Turns out Naga is lexical scoping instead of functional/modulo scoping and they are changing that in gfx-rs/naga#2065

### PR DESCRIPTION
**Pull request by haoyunfeix**
FIXES #6842
Declare user defined function before entry point function to support shader translation library which does not implement module scoping yet, like naga(https://github.com/gfx-rs/naga/pull/2075)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6918)

### CODE REVIEW

**Comment by hujiajie** [comment]
Can we add a [generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) function `foobar()` in `webgpu_program.ts`, call the first step of `foobar()` in `getMainHeaderString()` and get a string like `fn main()`, then after `getUserCode()` returns, call the second step of `foobar()` to get the matching definition of `_start()`?

**Comment by haoyunfeix** [comment]
@qjia7 @xhcao @axinging @hujiajie @gyagp PTAL

File: tfjs-backend-webgpu/src/scatter_webgpu.ts [hunk 1]
```diff
@@ -49,7 +50,7 @@ export class ScatterProgram implements WebGPUProgram {
     this.shaderKey = `scatter_${indicesRank}_${updatesRank}_${
         this.sliceDimGreaterThanOne}_${outputDtype}_${sumDupeIndices}`;
     const stridesType = getCoordsDataType(strides.length);
-    this.uniforms = `sliceDim : i32, strides: ${stridesType}, size: i32,`;
+    this.uniforms = `sliceDim : i32, strides: ${stridesType}, sizeUpdate: i32,`;
```
Comment (gyagp) [inline tfjs-backend-webgpu/src/scatter_webgpu.ts:53]: sizeUpdate -> updateSize?

File: tfjs-backend-webgpu/src/webgpu_program.ts [hunk 2]
```diff
@@ -144,6 +124,26 @@ export function getMainHeaderString(...params: string[]): string {
   return snippet;
 }
 
+export function getStartHeaderString(isUseIndex: boolean): string {
```
Comment (qjia7) [inline tfjs-backend-webgpu/src/webgpu_program.ts:127]: rename: `isUseIndex` -> `useGlobalIndex`?

File: tfjs-backend-webgpu/src/webgpu_program.ts [hunk 3]
```diff
@@ -160,8 +160,10 @@ function makeShader(
       const workGroupSizeZ = ${program.workGroupSize[2]}u;
 
       var<private> localId: vec3<u32>;
+      var<private> localIndex: u32;
       var<private> globalId: vec3<u32>;
       var<private> numWorkgroups: vec3<u32>;
+      var<private> workGroupId: vec3<u32>;
```
Comment (qjia7) [inline tfjs-backend-webgpu/src/webgpu_program.ts:166]: `workGroupId` -> `workgroupId`

File: tfjs-backend-webgpu/src/webgpu_program.ts [hunk 4]
```diff
@@ -198,6 +198,7 @@ function makeShader(
       prefixSnippets.join('\n'),
       getCoordsFromIndexSnippet(outputData.shape),
       program.getUserCode(),
+      getStartHeaderString(program.size),
```
Comment (qjia7) [inline tfjs-backend-webgpu/src/webgpu_program.ts:201]: Maybe just use `getStartHeaderString(true)` so that you don't need to change `from_pixels_webgpu.ts`?

File: tfjs-backend-webgpu/src/webgpu_program.ts [hunk 5]
```diff
@@ -170,11 +172,9 @@ function makeShader(
...
                    localId.y * workGroupSizeX + localId.x;
-               let workGroupID = (globalId - localId)/vec3<u32>(
-                   workGroupSizeX, workGroupSizeY, workGroupSizeZ);
 
-               return i32((workGroupID.z * numWorkgroups.x * numWorkgroups.y +
-                   workGroupID.y * numWorkgroups.x + workGroupID.x) *
+               return i32((workGroupId.z * numWorkgroups.x * numWorkgroups.y +
+                   workGroupId.y * numWorkgroups.x + workGroupId.x) *
                    (workGroupSizeX * workGroupSizeY * workGroupSizeZ) +
                    localInvocationIndex);
```
Comment (qjia7) [inline tfjs-backend-webgpu/src/webgpu_program.ts:179]: The `localInvocationIndex` can also be replaced by `localIndex`?

**Review by qjia7 — COMMENTED** [review]
`program.size` seems not a good name. But we can do the renaming in a separate PR.

File: tfjs-backend-webgpu/src/webgpu_program.ts (hunk 4 above)
Comment (qjia7) [reply tfjs-backend-webgpu/src/webgpu_program.ts:201]: A second thought, I prefer we use whether it's a flat dispatch layout to be as the parameter of `getStartHeaderString`, which is easier to understand. And same for L283.
```
const isFlatDispatchLayout = (program.dispatchLayout.y === null && program.dispatchLayout.z === null) || (program.dispatchLayout.y.length === 0 && program.dispatchLayout.z.length ===0)
getStartHeaderString(isFlatDispatchLayout )

File: tfjs-backend-webgpu/src/matmul_packed_webgpu.ts [hunk 6]
```diff
@@ -178,23 +180,15 @@ export function makeMatMulPackedVec4Source(
...
+  ${main()} {
     let localRow = i32(localId.y);
     let tileRow = ${isVectorA ? '0' : 'localRow * RowPerThread'};
     let tileCol = i32(localId.x);
 
     let globalRow = ${isVectorA ? '0' : 'i32(globalId.y) * RowPerThread'};
     let globalCol = i32(globalId.x);
     let batch = ${splitK ? '0' : 'i32(globalId.z)'};
-    let globalRowStart = i32(workgroupId.y) * ${tileAOuter};
+    let globalRowStart = i32(workGroupId.y) * ${tileAOuter};
```
[the remark this answers is not in the document]
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/matmul_packed_webgpu.ts]: Updated.

File: tfjs-backend-webgpu/src/scatter_webgpu.ts (hunk 1 above)
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/scatter_webgpu.ts]: Updated.

File: tfjs-backend-webgpu/src/depthwise_conv2d_nchw_shared_webgpu.ts [hunk 7]
```diff
@@ -116,11 +112,12 @@ export class DepthwiseConv2DNCHWSharedProgram implements WebGPUProgram {
         }
 
         // Load one tile of W into local memory.
-        var wIndex = localIndex;
+        var wIndex = localIndexI;
```
[the remark this answers is not in the document]
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/depthwise_conv2d_nchw_shared_webgpu.ts]: Yes, updated.

File: tfjs-backend-webgpu/src/webgpu_program.ts (hunk 2 above)
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/webgpu_program.ts]: Updated.

File: tfjs-backend-webgpu/src/webgpu_program.ts (hunk 3 above)
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/webgpu_program.ts]: Done.

File: tfjs-backend-webgpu/src/webgpu_program.ts (hunk 5 above)
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/webgpu_program.ts]: Yes, that may also reduce computing cost.

**Review by gyagp — APPROVED** [review]
LGTM. We need another PR to change all the occurrences of workgroup to a single word.

File: tfjs-backend-webgpu/src/depthwise_conv2d_webgpu.ts [hunk 8]
```diff
@@ -65,70 +66,74 @@ export class DepthwiseConv2DProgram implements WebGPUProgram {
...
+                  }
+
+                  let xVal = ${getXSnippet};
+                  let wVal = getW(wR, wC, d1, q);
+                  value = value + xVal * wVal;
+                }
               }
             }
+            ${biasActivationSnippet(this.addBias, this.activation)}
+          if (coordsInBounds4D(coords, uniforms.outShape)) {
```
Comment (qjia7) [inline tfjs-backend-webgpu/src/depthwise_conv2d_webgpu.ts:134]: Since you already used `if (index < uniforms.size)`, `if (coordsInBounds4D(coords, uniforms.outShape))` is not needed anymore.

**Review by qjia7 — APPROVED** [review]
LGTM with one nit.

File: tfjs-backend-webgpu/src/depthwise_conv2d_webgpu.ts (hunk 8 above)
Comment (haoyunfeix) [reply tfjs-backend-webgpu/src/depthwise_conv2d_webgpu.ts]: Thanks, updated.
